Add a command override for ec2-connect

diff --git a/aws/ec2-connect b/aws/ec2-connect
--- a/aws/ec2-connect
+++ b/aws/ec2-connect
@@ -23,6 +23,7 @@ CACHE_ARG=''
 FILTER_TERM=''
 TASK='_conn'
 OVERRIDE_HOST=''
+OVERRIDE_CMD=''
 
 SSH_USER=${EC2_CONNECT_DEFAULT_USER:-ec2-user}
 KEY="${EC2_CONNECT_DEFAULT_KEY:-$HOME/.ssh/id_rsa}"
@@ -75,6 +76,7 @@ usage() {
   echo '--scp        Instead of connecting to the host, print an scp command'
   echo '             which can easily be used to copy files to/from the host'
   echo '--user USER  Use the specified user.'
+  echo '--cmd CMD    Run the provided command instead of a bash shell'
   echo ''
   echo 'FILTER    Filter instances by this term before presenting choices.'
   echo '          If there is exactly one match for the term it will be '
@@ -94,8 +96,14 @@ _conn() {
     OVERRIDE_PS1=$("$REMOTE_PS1_SCRIPT" "$INSTANCE_NAME")
   fi
 
-  # Stick my PS1 override into a bashrc and start a shell using that one
-  LAUNCH_CMD="cp ~/.bashrc ~/.bashrc.n && echo 'export PS1="'"'"$OVERRIDE_PS1"'"'"' >> ~/.bashrc.n; bash --rcfile ~/.bashrc.n"
+
+  if [[ "$OVERRIDE_CMD" ]]; then
+    # Override the whole launch command if --cmd was specified
+    LAUNCH_CMD="$OVERRIDE_CMD"
+  else
+    # Stick my PS1 override into a bashrc and start a shell using that one
+    LAUNCH_CMD="cp ~/.bashrc ~/.bashrc.n && echo 'export PS1="'"'"$OVERRIDE_PS1"'"'"' >> ~/.bashrc.n; bash --rcfile ~/.bashrc.n"
+  fi
   echo "${YELLOW}Connecting to instance $INSTANCE_NAME ($IP)$RESET"
 
   ssh -t -i "$KEY" "$SSH_USER@$IP" "$LAUNCH_CMD"
@@ -134,6 +142,11 @@ while [[ "$#" != 0 ]]; do
       OVERRIDE_HOST="$1"
       shift
       ;;
+    -c|--cmd)
+      shift
+      OVERRIDE_CMD="$1"
+      shift
+      ;;
     --help)
       usage
       exit 0
@@ -153,6 +166,11 @@ while [[ "$#" != 0 ]]; do
       ;;
   esac
 done
+
+if [[ "$OVERRIDE_CMD" != '' && "$TASK" == '_print_scp' ]]; then
+  echo 'The --cmd option cannot be used with the --scp flag' >&2
+  exit 1
+fi
 
 IP_PATTERN='([0-9]{1,3}\.){3}[0-9]{1,3}'
 
